name: Mirror to GitLab

on:
  push:
    branches:
      - main
      - docker

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        env:
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
        run: |
          git remote add gitlab https://${GITLAB_USERNAME}:${GITLAB_TOKEN}@git.ztu.edu.ua/ipz/2022-2026/ipz-22-4/skovlyuk-matviy/diplomaflowersdelivery.git
          git push gitlab HEAD:${GITHUB_REF_NAME}
